### ISSUE TITLE
spike-in normalization

### ISSUE THREAD

**Issue by jordan841220** [mbassalbioinformatics/CnRAP#2]
Thank you for developing this amazing pipeline!
My question might be naive but I could not find answers else where (or I ignored).

I have read that the value 10,000,000 was used in the calculation of scale factor during spike-in calibration:
`mapped_reads_per_file[sample_counter][2] = 10000000 / ( int(mapped_reads_per_file[sample_counter][0]) / 2 )`

However, I don't understand whether the value (10,000,000) was determined case by case? 
Since in another CUT&Tag pipeline, it was 10,000 (https://yezhengstat.github.io/CUTTag_tutorial/index.html#V_Spike-in_calibration).

If yes, how should one choose this constant value?

Thanks,
Jordan

**Comment by mbassalbioinformatics** [comment]
Hey, sorry for delay in getting back to you.
Yeah so the scaling factor is kinda arbitrary but its dependant on your sequencing. You really need a scaling factor that would be suitable (id say 5-20 really?). So you need to figure out based on your dataset and your number of aligned reads, what scaling factor will work for you best.  When developing CnRAP, like you, I saw 10,000 used regularly, but for my datasets that was proving to be not ideal, so i went larger.

With that said though, if your analysis can wait another couple of weeks, id suggest you instead use [CaRAS](https://github.com/JSuryatenggara/CARAS). This is our new Cut&Run/Tag specific end-end pipeline. Were just putting final touchups on a few things in the the scripts, but, aim to have a new release for it in 2-3 weeks or so. 

CaRAS takes a lot from our published ChIP-Seq pipeline, [ChIP-AP](https://github.com/JSuryatenggara/ChIP-AP), but is tuned specifically for C&R/T. There are a couple of steps we have developed for processing and analysis that are unique only to our workflow which from our testing really improve the end result. CaRAS is also entirely automated, its 1 command line call and it takes care of everything from cleanup, alignment, normalization, peak calling (using 6 peak callers), and if you want, motif enrichment and pathway analysis as well. So id really suggest waiting for the next release (2-3 weeks) and using that instead. Your results will thank you for it :)

If you want, reach out to us via [email](https://connects.catalyst.harvard.edu/Profiles/display/Person/164665) and we can discuss through other channels.

**Comment by jordan841220** [comment]
@mbassalbioinformatics 
Great explanation. Reaching you through the email!

Jordan
